#企业微信应用通知参数配置
#下方填入企业微信应用以及plex相关的参数,xxxxx就是需要自己填的，引号保留，只改xxxx，appcode按需修改
#企业微信应用消息官方文档可参考：https://developer.work.weixin.qq.com/document/path/90854#%E5%9B%BE%E6%96%87%E6%B6%88%E6%81%AF
wxapp:
  corpid: "xxxxxx"   #企业ID 
  secret: "xxxxxx"   #企业应用的密钥
  agentid: "xxxxxx"  #应用ID 通常是 1000008 这样的格式
  touser: "xxxxxx"   #接收通知的账号: 进入企微后台-应用管理-点用于发通知的应用-鼠标悬停在管理员的小卡片-弹出小弹窗中的账号就是需要填这里的，特殊情况填"@all"(注意引号必须有)所有人都可收到通知。
  msgtype: "news"       #可选消息类型 news(图文消息) textcard(卡片消息，不展示影片海报图) text(纯文本)
  plex_server_url: "https://xxxxxx.com:32400"     #外网 plex 服务器地址，能外网访问的域名地址，非443端口记得加端口号。若填内网地址，推送图片只在内网才可查看到，外网时图片无法显示
  picurl_default: "https://raw.githubusercontent.com/Alano-i/wecom-notification/main/Plex/pic/plex_default.png"   #通知缺省背景图，当没有获取到背景封面时调用此图
  picurl_music_default: "https://github.com/Alano-i/wecom-notification/blob/main/Plex/pic/plex_music_defeat.jpg"   # 通知音乐背景图，当没有获取到背景封面时调用此图
  PLEX_TOKEN: "xxxxxx"     #plex身份认证，否则无法获取封面背景图，获取方式：在plex中随意点开一部影片封面右下角3个点，然后选择获取信息，再点弹窗左下角的查看xml会跳转链接,查看浏览器地址栏有X-Plex-Token字样
  appcode: ""            #配置正确的appcode可展示客户端ip归属地。该值为空则不展示。appcode获取方法（显示归属地其实没什么用，保持为空即可。如果一定要用，下面是方法）：在阿里云市场获取免费的IP归属地解析试用 https://reurl.cc/V1mN0N  进入管理控制台，在已购买的服务中可以找到AppCode
  thumb_media_id: ""  # 服务器有更新时调用的图片，此图片存储在企业微信素材库的，获取方法可参考 https://alanoo.notion.site/thumb_media_id-64f170f7dcd14202ac5abd6d0e5031fb
  # 注意：thumb_media_id 如果不知道怎么设置就保持默认为空（收到的消息没有图片），不要随便设置，随便设置收不到通知
  translate_switch: "on"             # 是否开启更新日志翻译，如果网络环境不支持或不想翻译设置为：off ，否则设置为：on，如果网络环境不支持还设置为 on，将会报错
  app_id: ""                         # 在百度翻译开放平台获取 APP_ID
  secret_key: ""                     # 在百度翻译开放平台获取 SECRET_KEY
  wecom_proxy_url: ""                # 企业微信的IP白名单代理域名设置，不明白什么意思不要随意设置，保持默认为空，格式为：https://abc.com，关于怎么自建企业微信代理我也不会。                          
                            
